# fly.toml app configuration file generated for habitask-web on 2024-01-22T21:35:04-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "habitask-web"
primary_region = "iad"

[build]

[env]
NODE_ENV="development"
VITE_BASE_URL="https://habitask-web.fly.dev"
VITE_HABITASK_API_URL="https://habitask-api.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
